### PR TITLE
simplified release distribution

### PR DESCRIPTION
**Pull request by FND**
> we don't want Yet Another Config File

WDYT, @moonglum?

### CODE REVIEW

**Comment by moonglum** [comment]
I find this utterly distasteful, but I guess it does the job.

**Comment by FND** [comment]
I ain't keen either, but it seems better than having a separate `faucet.config.dist.js` pollute the root directory?

**Comment by moonglum** [comment]
Agreed. But please call it DIST... I think the name of the library doesn't add anything to the name.

**Comment by FND** [comment]
Except it's a shared namespace, so `DIST` _might_ clash with some other application/process/whatever?

**Comment by moonglum** [comment]
You're too paranoid.

**Comment by FND** [comment]
Merged as aef507a55d465453885c55737e89bd7a48671be1, using `Object.assign` to (arguably, slightly) improve readability.

**Pull request closed without merging**
